name: Deploy to GCP Cloud Run

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: forum-restapi
    REGION: europe-west4
    REPO_NAME: forumapi-repo
    SERVICE_NAME: forum-api

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Secrets environments

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Fetch Secrets from GCP Secret Manager
              run: |
                  echo "JWT_SECRET=$(gcloud secrets versions access latest --secret=jwt-secret)" >> $GITHUB_ENV
                  echo "JWT_REFRESH_SECRET=$(gcloud secrets versions access latest --secret=jwt-refresh-secret)" >> $GITHUB_ENV
                  echo "GCS_BUCKET_NAME=$(gcloud secrets versions access latest --secret=gcp-bucket-name)" >> $GITHUB_ENV
                  echo "POSTGRES_DB=$(gcloud secrets versions access latest --secret=postgres-db)" >> $GITHUB_ENV
                  echo "POSTGRES_USER=$(gcloud secrets versions access latest --secret=postgres-user)" >> $GITHUB_ENV
                  echo "POSTGRES_PASSWORD=$(gcloud secrets versions access latest --secret=postgres-password)" >> $GITHUB_ENV

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run Prettier check
              run: npm run format:check

            - name: Run ESLint
              run: npm run lint

            - name: Validate OpenAPI spec
              run: npm run validate

            # - name: Set JWT_SECRET
            #   run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

            # - name: Set JWT_REFRESH_SECRET
            #   run: echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> $GITHUB_ENV

            # - name: Set GCS_BUCKET_NAME
            #   run: echo "GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}" >> $GITHUB_ENV

            # - name: Set POSTGRES_DB
            #   run: echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV

            # - name: Set POSTGRES_USER
            #   run: echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV

            # - name: Set POSTGRES_PASSWORD
            #   run: echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV

            - name: Run Tests
              run: npm test

            - name: Set up gcloud CLI
              uses: google-github-actions/setup-gcloud@v1

            - name: Configure Docker
              run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

            - name: Build Docker Image
              run: docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest .

            - name: Push Docker Image
              run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest

            - name: Validate service.yml
              run: |
                  gcloud run services replace service.yml --dry-run \
                    --region ${{ env.REGION }} \
                    --platform managed \
                    --project ${{ env.PROJECT_ID }} \
                    --dry-run

            - name: Apply service.yml configuration
              run: |
                  gcloud run services replace service.yml \
                    --region ${{ env.REGION }} \
                    --platform managed \
                    --project ${{ env.PROJECT_ID }}

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy ${{ env.SERVICE_NAME }} \
                    --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest \
                    --region ${{ env.REGION }} \
                    --platform managed \
                    --project ${{ env.PROJECT_ID }}
